on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4

    - name: Build
      shell: bash -l {0}
      run: |
        nvm use lts/gallium
        npm install
        npm run all

    - run: |
        echo '$schema: https://raw.githubusercontent.com/oyvindberg/bleep/master/schema.json' >> bleep.yaml
        echo '$version: 0.0.1-M24' >> bleep.yaml
        echo 'projects:' >> bleep.yaml
        echo '  a: {}' >> bleep.yaml

    - id: bleep-setup
      uses: ./

    - run: echo $PATH

    # test bleep
    - run: bleep projects
